config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/data_provider.rb
class DataProvider
  include Singleton

  attr_accessor :orders

  def initialize
    file = File.read('./data/orders.json')
    @orders = JSON.parse(file).map do |item|
      order_items = item["items"].map do |i|
        OrderItem.new(
          name: i["name"],
          size: i["size"],
          add: i["add"],
          remove: i["remove"]
        )
      end
      Order.new(
        id: item["id"],
        created_at: DateTime.parse(item["createdAt"]),
        state: item["state"],
        items: order_items,
        promotion_codes: item["promotionCodes"],
        discount_code: item["discountCode"]
      )
    end
  end
end

app/models/order.rb
class Order

  attr_reader :id, :created_at, :items, :promotion_codes, :discount_code
  attr_accessor :state

  def initialize(id:, created_at:, state:, items:, promotion_codes:, discount_code:)
    @id = id
    @created_at = created_at
    @state = state
    @items = items
    @promotion_codes = promotion_codes
    @discount_code = discount_code
  end

  def total_price
    @price_calculator ||= PriceCalculator.new(order: self)
    @price_calculator.call.round(2)
  end
end

app/models/order_item.rb
class OrderItem
  attr_reader :name, :size, :add, :remove

  def initialize(name:, size:, add:, remove:)
    @name = name
    @size = size
    @add = add
    @remove = remove
  end
end

app/models/price_calculator.rb
class PriceCalculator
  attr_reader :config, :order

  def initialize(order:)
    @config = YAML.load_file('./data/config.yml')
    @order = order
  end

  def call
    price = calculate_pizza_price

    price = price - get_promo_codes_discount
    price = price - get_discount(price)

    price.round(2)
  end

  private

  def calculate_pizza_price
    prices = order.items.map do |item|
      base_price = config["pizzas"][item.name].to_f
      size_multiplier = config["size_multipliers"][item.size].to_f
      ingredient_prices = item.add.map do |ing|
        config["ingredients"][ing].to_f * size_multiplier
      end
      base_price * size_multiplier + ingredient_prices.sum
    end
    prices.sum
  end

  def get_promo_codes_discount
    unless order.promotion_codes.empty?
      promos = order.promotion_codes.map do |promo|
        promotion = config["promotions"][promo]
        target = promotion["target"]
        target_size = promotion["target_size"]
        from = promotion["from"]
        to = promotion["to"]

        found_items = order.items.filter {|el| el.name == target && el.size == target_size}
        if found_items.count >= from
          item = found_items[0]
          base_price = config["pizzas"][item.name].to_f
          size_multiplier = config["size_multipliers"][item.size].to_f
          item_price = base_price * size_multiplier

          discount = item_price * (found_items.count / from).to_i * to
          discount
        end
      end
      price_reduce = promos.compact.sum
      price_reduce
    else
      0
    end
  end

  def get_discount(price)
    if order.discount_code
      discount = config["discounts"][order.discount_code]["deduction_in_percent"]
      price * discount.to_f / 100.0
    else
      0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  attr_reader :orders

  def index
    orders = DataProvider.instance.orders
    @orders = orders.filter {|o| o.state != "COMPLETE"}
  end

  def update
    order_id = params[:id]
    orders = DataProvider.instance.orders
    order_to_complete = orders.find {|order| order.id == order_id}
    order_to_complete.state = "COMPLETE"

    redirect_to action: "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>
<hr>
<table>
<% @orders.each do |order| %>

<tr valign="top">
    <td>
    ID: <%= order.id %><br>
    Created: <%= order.created_at.strftime('%B %e, %Y %H:%M') %><br>
    Promotion codes: <%= order.promotion_codes %><br>
    Discount codes: <%= order.discount_code %><br>
        Total price: <%= order.total_price %>€<br>
    <%= button_to "Complete", order_path(order.id), :method => :patch, data: { turbo: false } %>
    </td>

    <td>
    Items: <% order.items.each do |item| %><br>
        • <%= item.name%>(<%= item.size %>)
        <% if !item.add.empty? %>
            <br> ◦ Add: <%= item.add.join(', ').html_safe %>
        <% end %>
        <% if !item.remove.empty? %>
            <br>◦ Remove: <%= item.remove.join(', ').html_safe %>
        <% end %>

    <% end %><br><br>

    </td>
</tr>


<% end %>
</table>